### ISSUE TITLE
Composant filtre multi-select : régler le problème de hauteur quand une valeur est sélectionnée

### ISSUE THREAD

**Issue by AdelineCelier** [MTES-MCT/monitor-ui#657]
Reprise du ticket [#2020](https://github.com/MTES-MCT/monitorfish/issues/2020) (côté Fish). 
Mettre à jour le composant dans Fish et Env dans l'idéal. 

![image](https://github.com/MTES-MCT/monitor-ui/assets/71878648/f8af348e-ee80-4520-b432-9997275e8697)

**Comment by louptheron** [comment]
@claire2212 En effet le fait d'avoir une recherche aide bien!

+1 pour `CheckPicker`

**Comment by ivangabriele** [comment]
+1 aussi. Et je suis pour passer le MultiSelect en `@deprecated` du coup et d'en faire un nouveau en gardant le nom Rsuite comme propose Thomas.

**Comment by claire2212** [comment]
@ivangabriele je pense qu'on peut garder le multI-select il est utilisé dans la sélection des moyen par exemple, avec l'affichage des tags


![Image](https://github.com/MTES-MCT/monitor-ui/assets/23258718/b37cd75a-3ee6-4cca-80c5-cc871cfd72be)
